### ISSUE TITLE
run  simple.py

### ISSUE THREAD

**Issue by DYF-AI** [mehdidc/pixel_to_svg#2]
Dear Author：
```shell
$ python3 simple.py
Traceback (most recent call last):
  File "simple.py", line 25, in <module>
    svg = to_svg(img, seg)
  File "/usr/local/lib/python3.8/dist-packages/pixel_to_svg-0.1.0-py3.8.egg/pixel_to_svg/pixel_to_svg.py", line 35, in to_svg
  File "/usr/local/lib/python3.8/dist-packages/pixel_to_svg-0.1.0-py3.8.egg/pixel_to_svg/pixel_to_svg.py", line 121, in binary_image_to_svg2
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/svg_to_paths.py", line 217, in svg2paths2
    return svg2paths(svg_file_location=svg_file_location,
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/svg_to_paths.py", line 144, in svg2paths
    if os_path.dirname(svg_file_location) == '':
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _io.StringIO
```
When I run simple.py, the above error appears...

**Comment by mehdidc** [comment]
Hi, sorry for the late answer, did you install my fork of svgpathtools (https://github.com/mehdidc/svgpathtools) or the original one ? in case you used the original one, please instead use my fork
